name: ont-guppy
owner: jdv
description: Guppy - nanopore basecalling software from ONT
#homepage_url: 
long_description: |
    Guppy is the current official ONT software tool for offline basecalling of
    Oxford Nanopore sequencing reads.
remote_repository_url: https://github.com/jvolkening/galaxy-tools/tree/master/tools/guppy
type: unrestricted
categories:
  - Sequence Analysis
