name: porechop
owner: jdv
description: Porechop - demultiplexing and adapter trimming of Oxford Nanopore reads
homepage_url: https://github.com/rrwick/Porechop
long_description: |
    Porechop is a tool for finding and removing adapters from Oxford Nanopore
    reads. Adapters on the ends of reads are trimmed off, and when a read has an
    adapter in its middle, it is treated as chimeric and chopped into separate
    reads. Porechop performs thorough alignments to effectively find adapters,
    even at low sequence identity.

    Porechop also supports demultiplexing of Nanopore reads that were barcoded
    with the Native Barcoding Kit, PCR Barcoding Kit or Rapid Barcoding Kit.
remote_repository_url: https://github.com/jvolkening/galaxy-tools/tree/master/tools/porechop
type: unrestricted
categories:
- Sequence Analysis
- Fasta Manipulation
- Fastq Manipulation
