name: b2b_utils
owner: jdvolkening
description: b2b-utils - bioinformatics utilities from BASE2BIO
homepage_url: https://github.com/jvolkening/b2b-utils
long_description: |
    A varied set of utilities for genomics and sequence analysis released by BASE2BIO.
remote_repository_url: https://github.com/jvolkening/galaxy-tools/tree/master/tools/b2b_utils
type: unrestricted
categories:
  - Sequence Analysis
exclude:
  - dev
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for B2B utility {{ tool_name }}."
suite:
  name: "suite_b2b_utils"
  description: "A suite of Galaxy tools wrapping several utilities from b2b-utils"
  type: repository_suite_definition
    
